name: Linux Container Node Workflow

on: [push]
env:
      MODULE_ORG : admin
      MODULE_NAME : workspace-factory-gcp
      MODULE_VERSION : 3
jobs:
  pack:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Pack Module 
      run: |
              echo $GIT_COMMIT_SHORT
              apiResults=$(curl https://reqres.in/api/products/"$MODULE_VERSION")
              echo $apiResults
              
